### ISSUE TITLE
CRSF token Issue

### ISSUE THREAD

**Issue by neilhanekom** [Marthyn/angularjs-file-upload-rails#8]
Rails controller doesnt accept the upload form. I get a CSRF token error

**Comment by Marthyn** [comment]
I don't it's the job of this gem to provide a CSRF token. 

If you use Rails form helpers the token is added automatically. 

For remote forms, there will be the same token in a meta tag if <%= csrf_meta_tag %> is added in the layout view. If the token is still not there check application.js for //= require jquery_ujs for the unobtrusive JQuery plugin.

The unobtrusive JQuery script will add that token automatically to Ajax requests as an HTTP header called “X-CSRF-Token” or a parameter called authenticity_token (if the form is dynamically created). If for some reason you can’t use that script, look at this [answer](http://stackoverflow.com/questions/7203304/warning-cant-verify-csrf-token-authenticity-rails).

[source](https://rorsecurity.info/portfolio/cross-site-request-forgery-and-rails)
